version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app.py:/app.py
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: bridge
