version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    build: .
    restart: on-failure:10
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    volumes:
      - ./:/app
      - ./db/db_client.py:/db/db_client.py

volumes:
  db:
